// Parameters for infra/main.bicep, from the environment's settings
// (.azure/<env>/.env). scripts/bootstrap.sh exports the settings that have
// a value before it deploys the stack; the rest take the defaults here.
using './main.bicep'

param environmentName = readEnvironmentVariable('AZURE_ENV_NAME')
param location = readEnvironmentVariable('AZURE_LOCATION', 'eastus2')
param apiImage = readEnvironmentVariable('USNM_API_IMAGE', '')
param searchBackend = readEnvironmentVariable('USNM_SEARCH_BACKEND', 'fixtures')
param ingestJobs = bool(readEnvironmentVariable('USNM_INGEST_JOBS', 'false'))
param useAcr = bool(readEnvironmentVariable('USNM_USE_ACR', 'false'))
param imageTag = readEnvironmentVariable('USNM_IMAGE_TAG', 'main')
param ingestCron = readEnvironmentVariable('USNM_INGEST_CRON', '')
param ingestFull = bool(readEnvironmentVariable('USNM_INGEST_FULL', 'false'))
param americanStories = bool(readEnvironmentVariable('USNM_AMERICAN_STORIES', 'false'))
param jaLatin = bool(readEnvironmentVariable('USNM_JA_LATIN', 'false'))
param partitionDecade = bool(readEnvironmentVariable('USNM_PARTITION_DECADE', 'false'))
param dedicatedProfile = bool(readEnvironmentVariable('USNM_DEDICATED_PROFILE', 'false'))
param ingestOnDedicated = bool(readEnvironmentVariable('USNM_INGEST_ON_DEDICATED', 'false'))
param archiveAccountId = readEnvironmentVariable('USNM_ARCHIVE_ACCOUNT', '')
param retainRaw = bool(readEnvironmentVariable('USNM_RETAIN_RAW', 'false'))
param backfillWorkers = int(readEnvironmentVariable('USNM_BACKFILL_WORKERS', '4'))
param backfillCron = readEnvironmentVariable('USNM_BACKFILL_CRON', '')
param ingestScratchGiB = int(readEnvironmentVariable('USNM_INGEST_SCRATCH_GIB', '128'))
param ingestMergeTimeoutSecs = int(readEnvironmentVariable('USNM_MERGE_TIMEOUT_SECS', '14400'))
param cosmosFreeTier = bool(readEnvironmentVariable('USNM_COSMOS_FREE_TIER', 'true'))
param logDailyCapGb = readEnvironmentVariable('USNM_LOG_DAILY_CAP_GB', '')
param alertEmails = readEnvironmentVariable('USNM_ALERT_EMAILS', '')
param searchLogReaders = readEnvironmentVariable('USNM_SEARCH_LOG_READERS', '')
param ocr = bool(readEnvironmentVariable('USNM_OCR', 'false'))
param ocrSku = readEnvironmentVariable('USNM_OCR_SKU', 'F0')
param ocrUsers = readEnvironmentVariable('USNM_OCR_USERS', '')
param jaOcrJob = bool(readEnvironmentVariable('USNM_JA_OCR_JOB', 'false'))
param jaOcrReplicas = int(readEnvironmentVariable('USNM_JA_OCR_REPLICAS', '2'))
param searchCluster = bool(readEnvironmentVariable('USNM_SEARCH_CLUSTER', 'false'))
param searchClusterNodes = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_NODES', '1'))
param searchClusterIndexers = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_INDEXERS', '1'))
param searchClusterNodeVcpu = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_NODE_VCPU', '2'))
param searchClusterSplitSearches = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_SPLIT_SEARCHES', '0'))
param searchClusterRuntimeThreads = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_RUNTIME_THREADS', '0'))
param searchClusterSearchThreads = int(readEnvironmentVariable('USNM_SEARCH_CLUSTER_SEARCH_THREADS', '0'))
param searchCompareTags = readEnvironmentVariable('USNM_SEARCH_COMPARE_TAGS', '')
param searchLocalMode = readEnvironmentVariable('USNM_SEARCH_LOCAL_MODE', '')
param searchLocalIndex = readEnvironmentVariable('USNM_SEARCH_LOCAL_INDEX', '')
param searchLocalCacheGib = int(readEnvironmentVariable('USNM_SEARCH_LOCAL_CACHE_GIB', '40'))
param budgetStartDate = readEnvironmentVariable('USNM_BUDGET_START', '')
param dnsZoneName = readEnvironmentVariable('USNM_DNS_ZONE', '')
// Google Search Console domain verification, published at the apex next to SPF.
param dnsApexTxtValues = {
  'usnewsmap.com': ['google-site-verification=5KCwOzVrZH4QvucrU0UkbqJ1I1jYmjkKNnUuy78VTWg']
}
param availabilityFrequency = readEnvironmentVariable('USNM_AVAILABILITY_FREQUENCY', '900')
param apiCertificateId = readEnvironmentVariable('USNM_API_CERT_ID', '')
param siteCertificateId = readEnvironmentVariable('USNM_SITE_CERT_ID', '')
param wwwCertificateId = readEnvironmentVariable('USNM_WWW_CERT_ID', '')
param githubRepo = readEnvironmentVariable('USNM_GITHUB_REPO', 'tgoodyear/usnewsmap.com')
param githubRepoIds = readEnvironmentVariable('USNM_GITHUB_REPO_IDS', 'tgoodyear@116683/usnewsmap.com@1389862972')
